#:schema https://www.schemastore.org/prek.json

exclude = '^assets/'

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "check-yaml" },
  { id = "check-toml" },
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" }
]

[[repos]]
repo = "local"
hooks = [
  {
    id = "typstyle",
    name = "typstyle",
    description = "Check files with typstyle",
    entry = "typstyle",
    language = "rust",
    additional_dependencies = ["cli:typstyle:0.14.4"],
    types = ["file"],
    files = '\.typ$',
    args = ["--inplace"]
  }
]
